<?php
/**
 * This file is part of the Calendar package.
 *
 * PHP version 8
 *
 * @category PHP
 * @package  Calendar
 * @author   Rafael Paulino <rafaclasses@gmail.com>
 * @license  https://github.com/rafapaulino/PHP-Calendar/LICENSE BSD Licence
 * @link     https://github.com/rafapaulino/PHP-Calendar
 */

namespace Calendar;

use Illuminate\Support\Collection;
use Carbon\Carbon;
use DateTimeInterface;


class Events extends Calendar
{
    protected array $events;

    public function __construct(int $month, int $year, int $firstDayWeek = 0, bool $full = true)
    {
        parent::__construct($month, $year, $firstDayWeek, $full);
        $this->events = array();
    }

    /**
     * Add an event.
     *
     * @param string $event
     * @param DateTimeInterface $datetime
     * @param array|null $details
     * @param int $days
     *
     * @return void
     */
    public function addEvent(string $event, DateTimeInterface $datetime, ?array $details = null, int $days = 1): void
    {
        $eventData = [
            'event' => $event,
            'details' => $details,
            'datetime' => $datetime->format('Y-m-d H:i:s'),
        ];

        if ($days > 1) {
            $start = Carbon::instance($datetime)->startOfDay();
            $end = (clone $start)->addDays($days - 1)->endOfDay();
            $period = Carbon::instance($start)->toPeriod($end, '1 day');

            foreach ($period as $date) {
                $this->prependEvent($date->toDateString(), $eventData);
            }
        } else {
            $this->prependEvent($datetime->format('Y-m-d'), $eventData);
        }
    }

    /**
     * Prepend event data into the events array grouped by Y-m-d date key.
     *
     * @param string $dateKey
     * @param array $eventData
     *
     * @return void
     */
    protected function prependEvent(string $dateKey, array $eventData): void
    {
        if (array_key_exists($dateKey, $this->events)) {
            array_push($this->events[$dateKey], $eventData);
        } else {
            $this->events[$dateKey] = [$eventData];
        }
    }

    public function getEvents(): array
    {
        return $this->events;
    }

    public function getDays(): Collection
    {
        $days = parent::getDays(); // TODO: Change the autogenerated stub
        return $days->map(function($item) {
            if (array_key_exists($item->date,$this->events)) {
                $item->events = $this->events[$item->date];
            } else {
                $item->events = array();
            }
            return $item;
        });
    }
}